### ISSUE TITLE
Configure React Router

### ISSUE THREAD

**Issue by LiorKGOW** [LiorKGOW/dnd-Battle-Tracker#12]
- [ ] Add some basic pages that would have a button to navigate between them
- [ ] Add tests

**Comment by Charity10** [comment]
Hello @LiorKGOW can you please give more description on this ask 
I'm a first time contributor and i would love to work on this

**Comment by LiorKGOW** [comment]
Hi @Charity10 
I have already finished configuring React Router in this PR: https://github.com/LiorKGOW/dnd-Battle-Tracker/pull/13
Thank you for your interest ! :)
